
## Set Up

### Load Packages and Data

```{r load-packages, include = FALSE}
# install.packages("tidyverse")
# install.packages("broom")
# install.packages("readr")
# install.packages("ggplot2")
# install.packages("dplyr")
# install.packages("lubridate")

library(tidyverse)
library(broom)
library(readr)
library(ggplot2)
library(dplyr)
library(lubridate)
```

### Data Wrangling

```{r add-observation-year-column}
salamanders <- salamanders %>% 
  mutate(date = as.Date(date, format = "%m/%d/%Y")) %>% 
  mutate(year = lubridate::year(date))
```

```{r create-range-object-for-range-analysis}
range <- salamanders %>%
  filter(pit != "none",
         pit != "not scanned",
         pit != "unknown") %>%
  group_by(pit, year, sex, first_year) %>%
  count(pool) %>%
  arrange(pit) %>%
  mutate(range = length(pool)) %>% 
  select(pit, year, sex, first_year, range) %>% 
  mutate(sex = case_when(
    pit == "243206" ~ "m",
    pit == "243207" ~ "m",
    pit == "243209" ~ "m",
    pit == "243210" ~ "m",
    pit == "243211" ~ "m",
    pit == "243212" ~ "m",
    pit == "243215" ~ "m",
    pit == "243216" ~ "m",
    pit == "243218" ~ "m",
    pit == "243220" ~ "m",
    pit == "243223" ~ "m",
    pit == "243227" ~ "m",
    pit == "243228" ~ "m",
    pit == "243229" ~ "m",
    pit == "243230" ~ "m",
    pit == "243231" ~ "f",
    pit == "243234" ~ "m",
    pit == "243235" ~ "f",
    pit == "243236" ~ "m",
    pit == "243237" ~ "m",
    pit == "243241" ~ "m",
    pit == "243242" ~ "m",
    pit == "243243" ~ "m",
    pit == "243244" ~ "f",
    pit == "243245" ~ "f",
    pit == "243246" ~ "m",
    pit == "243248" ~ "m",
    pit == "243250" ~ "m",
    pit == "243251" ~ "m",
    pit == "243253" ~ "m",
    pit == "243254" ~ "m",
    pit == "243255" ~ "m",
    pit == "243257" ~ "m",
    pit == "243258" ~ "m",
    pit == "243259" ~ "m",
    pit == "243260" ~ "m",
    pit == "243261" ~ "m",
    pit == "243262" ~ "f",
    pit == "243263" ~ "f",
    pit == "243264" ~ "m",
    pit == "243266" ~ "m",
    pit == "243272" ~ "f",
    pit == "243273" ~ "f",
    pit == "243274" ~ "m",
    pit == "243275" ~ "m",
    pit == "243276" ~ "m",
    pit == "243279" ~ "m",
    pit == "243281" ~ "m",
    pit == "243282" ~ "m",
    pit == "243283" ~ "m",
    pit == "243284" ~ "f",
    pit == "243286" ~ "m",
    pit == "243287" ~ "m",
    pit == "243289" ~ "m",
    pit == "243290" ~ "m",
    pit == "243292" ~ "m",
    pit == "243293" ~ "m",
    pit == "243300" ~ "m",
    pit == "243304" ~ "m",
    pit == "243305" ~ "m",
    pit == "243309" ~ "f",
    pit == "243311" ~ "m",
    pit == "243315" ~ "f",
    pit == "243318" ~ "m",
    pit == "243319" ~ "m",
    pit == "243320" ~ "m",
    pit == "243321" ~ "m",
    pit == "243322" ~ "m",
    pit == "243324" ~ "f",
    pit == "243326" ~ "m",
    pit == "243327" ~ "m",
    pit == "243328" ~ "m",
    pit == "243329" ~ "f",
    pit == "243329" ~ "m",
    pit == "243330" ~ "m",
    pit == "243331" ~ "f",
    pit == "243332" ~ "m",
    pit == "243337" ~ "m",
    pit == "243339" ~ "f",
    pit == "243341" ~ "m",
    pit == "243343" ~ "m",
    pit == "243345" ~ "m",
    pit == "243348" ~ "m",
    pit == "243350" ~ "f",
    pit == "243351" ~ "m",
    pit == "243352" ~ "m",
    pit == "243354" ~ "m",
    pit == "243355" ~ "m",
    pit == "243357" ~ "f",
    pit == "243358" ~ "m",
    pit == "243361" ~ "m",
    pit == "243362" ~ "f",
    pit == "243363" ~ "m",
    pit == "243365" ~ "f",
    pit == "243368" ~ "f",
    pit == "243370" ~ "f",
    pit == "243373" ~ "m",
    pit == "243374" ~ "m",
    pit == "243375" ~ "m",
    pit == "243377" ~ "m",
    pit == "243378" ~ "m",
    pit == "243379" ~ "m",
    pit == "243382" ~ "m",
    pit == "243383" ~ "m",
    pit == "243384" ~ "m",
    pit == "243386" ~ "m",
    pit == "243388" ~ "f",
    pit == "243389" ~ "m",
    pit == "243390" ~ "m",
    pit == "243396" ~ "m",
    pit == "243397" ~ "m",
    pit == "243399" ~ "m",
    pit == "243400" ~ "m",
    pit == "243401" ~ "m",
    pit == "243402" ~ "m",
    pit == "243403" ~ "m",
    pit == "243404" ~ "m",
    pit == "244720" ~ "m",
    pit == "244726" ~ "m",
    pit == "244741" ~ "m",
    pit == "244752" ~ "m",
    pit == "244755" ~ "f",
    pit == "244778" ~ "f",
    pit == "244830" ~ "m",
    pit == "244837" ~ "m",
    pit == "244851" ~ "m",
    pit == "244868" ~ "m",
    pit == "244880" ~ "m",
    pit == "244887" ~ "m",
    pit == "243359" ~ "f",
    .default = sex))
```

```{r remove-duplicate-rows}
range <- distinct(range)
```

## Data Exploration

### Sex 

```{r make-year-column}
salamanders %>% 
  mutate(year = str_extract(date, {"/dddd"}))
```

```{r histogram-range}
range %>% 
  ggplot(aes(range)) +
  geom_bar() +
  facet_wrap(~ year)
```

```{r count-total-sexed-pits}
total=unique(range$pit[range$sex=="m"])
length(total)

total=unique(range$pit[range$sex=="f"])
length(total)
```

```{r slice-first-range}
sex_range <- range %>% 
  filter(sex == "m" |
         sex == "f") %>% 
  group_by(pit) %>% 
  slice_head()
```

####  Sex Difference Analysis

```{r sex-range-view-distribution}
par(mfrow=c(3,1))
hist(sex_range$range[sex_range$year=="2022"])
hist(sex_range$range[sex_range$year=="2023"])
hist(sex_range$range[sex_range$year=="2024"])

par(mfrow=c(2,1))
hist(sex_range$range[sex_range$sex=="m"])
hist(sex_range$range[sex_range$sex=="f"])

boxplot(sex_range$range~sex_range$sex, ylab="range", xlab="sex")
```

```{r sex-range-wilcox-mf-22-24}
wilcox.test(range~sex,data=sex_range)
```

```{r boxplot-mf-all-years}
sex_range %>%
  mutate(sex = case_when(
    sex == "f" ~ "Female",
    sex == "m" ~ "Male"
  )) %>% 
  ggplot(aes(x=sex, y=range, fill=sex)) +
    geom_boxplot() +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  theme_bw() +
    labs(title = "Sex Differences in Range During Breeding Season",
         subtitle = "at Otter Point Across 3 Seasons: 2022-2024",
         x = "Sex",
         y = "Number of Breeding Pools",
         fill = "Sex")
```

```{r sex-differences-range-histogram}
sex_range %>%
  mutate(sex = case_when(
    sex == "f" ~ "Female",
    sex == "m" ~ "Male"
  )) %>% 
  ggplot(aes(x=range, fill=sex)) +
    geom_histogram() +
  facet_wrap(~ sex) +
  theme_bw() +
    labs(title = "Sex Differences in Range During Breeding Season",
         subtitle = "at Otter Point Across 3 Seasons: 2022-2024",
         x = "Number of Breeding Pools",
         y = "Number of Individuals",
         fill = "Sex")
```

```{r sex-differences-range-density}
sex_range %>%
  mutate(sex = case_when(
    sex == "f" ~ "Female",
    sex == "m" ~ "Male"
  )) %>% 
  ggplot(aes(x=range, fill=sex)) +
    geom_density(alpha = 0.5) +
    facet_wrap(~ sex) +
  theme_bw() +
    labs(title = "Sex Differences in Range During Breeding Season",
         subtitle = "at Otter Point Across 3 Seasons: 2022-2024",
         x = "Number of Breeding Pools",
         y = "Density of Observations",
         fill = "Sex")
```

### Age

```{r slice-first-range}
age_range <- range %>% 
  filter(sex == "m" |
         sex == "f") %>% 
  drop_na(first_year) %>% 
  group_by(pit) %>% 
  slice_head()
```


#### Age Difference Analysis
```{r view-distributions}
age_range %>% 
  filter(first_year != "2023",
         first_year != "2024") %>% #filtering out 2023 and 2024 because sample sizes are too small
  ggplot(aes(x = range)) +
  geom_histogram() +
  facet_wrap(~ first_year)

par(mfrow=c(3,3))
hist(sex_range$range[sex_range$first_year=="2017"])
hist(sex_range$range[sex_range$first_year=="2018"])
hist(sex_range$range[sex_range$first_year=="2019"])
hist(sex_range$range[sex_range$first_year=="2020_2021"])
hist(sex_range$range[sex_range$first_year=="2022"])
```

```{r age-range-boxplot}
age_range %>% 
  filter(first_year != "2023",
         first_year != "2024") %>% #filtering out 2023 and 2024 because sample sizes are too small
  mutate(first_year = case_when(
    first_year == "2017" ~ "8",
    first_year == "2018" ~ "7",
    first_year == "2019" ~ "6",
    first_year == "2020_2021" ~ "4-5",
    first_year == "2022" ~ "3"
  )) %>% 
  ggplot(aes(x = first_year, y = range)) +
  geom_boxplot() +
    geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme(
      legend.position="none",
      plot.title = element_text(size=11)
    ) +
  theme_bw() +
    labs(title = "Age Differences in Range During Breeding Season",
         subtitle = "at Otter Point, Across Three Seasons: 2022-2024",
         x = "Minimum Age (Years)",
         y = "Number of Breeding Pools")
```

```{r age-range-histogram}
age_range %>%
   filter(first_year != "2023",
         first_year != "2024") %>% #filtering out 2023 and 2024 because sample sizes are too small
  mutate(first_year = case_when(
    first_year == "2017" ~ "> 8 Years",
    first_year == "2018" ~ "> 7 Years",
    first_year == "2019" ~ "> 6 Years",
    first_year == "2020_2021" ~ "> 4-5 Years",
    first_year == "2022" ~ "> 3 Years"
  )) %>% 
  ggplot(aes(x=range)) +
    geom_histogram() +
  facet_wrap(~ first_year) +
  theme_bw() +
    labs(title = "Age Differences in Range During Breeding Season",
         subtitle = "at Otter Point, Across Three Seasons: 2022-2024",
         x = "Number of Breeding Pools",
         y = "Number of Salamanders")
```

```{r age-range-kruskal-test-22-24}
kruskal.test(range~first_year,data=age_range)
```


